In [1]:
import numpy as np

In [2]:
arr = [1,2,3,4,5]
np_arr = np.array(arr)

print(np_arr)
print(type(np_arr))
print(np.size(np_arr))

[1 2 3 4 5]
<type 'numpy.ndarray'>
5


In [3]:
a = np.arange(15)
b = a.reshape(3,5)
print a
print b

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [4]:
print(a+10)
print(a*10)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
[  0  10  20  30  40  50  60  70  80  90 100 110 120 130 140]


In [5]:
print np.zeros((3,4))
print np.ones((4,3))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [6]:
print np.arange(10,40,5) #start, end, step
print np.arange(0,2,0.3)

[10 15 20 25 30 35]
[0.  0.3 0.6 0.9 1.2 1.5 1.8]


In [7]:
a = np.arange(10)
b = np.sin(a)
print a
print b
print a**3
print np.max(b)
print np.mean(b)
print np.sum(b)

[0 1 2 3 4 5 6 7 8 9]
[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427
 -0.2794155   0.6569866   0.98935825  0.41211849]
[  0   1   8  27  64 125 216 343 512 729]
0.9893582466233818
0.195520948210738
1.9552094821073802


In [8]:
c = np.arange(15).reshape(3,5)
print c
print np.sum(c, axis = 0) #sum of each column
print np.sum(c, axis = 1) #sum of each row
print np.max(c, axis = 0)
print np.max(c, axis = 1)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[15 18 21 24 27]
[10 35 60]
[10 11 12 13 14]
[ 4  9 14]


In [9]:
a = np.arange(10)**3
print a[2]
print a[2:5]
print a[2:8:2]
print a
print a[::-1]

8
[ 8 27 64]
[  8  64 216]
[  0   1   8  27  64 125 216 343 512 729]
[729 512 343 216 125  64  27   8   1   0]


In [10]:
a = np.arange(15)
coefficients = [1,2,3]
f = np.poly1d(coefficients)
result = np.zeros((np.size(a),2))
result[0:,0] = a
result[0:,1] = f(a)

print result

[[  0.   3.]
 [  1.   6.]
 [  2.  11.]
 [  3.  18.]
 [  4.  27.]
 [  5.  38.]
 [  6.  51.]
 [  7.  66.]
 [  8.  83.]
 [  9. 102.]
 [ 10. 123.]
 [ 11. 146.]
 [ 12. 171.]
 [ 13. 198.]
 [ 14. 227.]]


In [11]:
a = np.arange(10)
print np.where(a>5)
print a%2
print a%2==0

(array([6, 7, 8, 9]),)
[0 1 0 1 0 1 0 1 0 1]
[ True False  True False  True False  True False  True False]
